global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.0.41:9093']

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['192.168.0.41:9090']
- job_name: 'your-app'
  static_configs:
  - targets: ['192.168.0.41:3001']
